"""Pydantic v2 models for the Goals System.

The Goals System is the human's primary interface for telling agents WHAT to build.
Humans express goals in natural language with minimal structure; the system handles
decomposition into actionable agent-sized tasks.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field

from src.intent.schema import RiskLevel


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class GoalPriority(str, enum.Enum):
    """How urgent / important a goal is."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class GoalStatus(str, enum.Enum):
    """Lifecycle status of a goal."""

    DRAFT = "draft"
    ACTIVE = "active"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class TaskStatus(str, enum.Enum):
    """Lifecycle status of an individual agent task."""

    PENDING = "pending"
    ASSIGNED = "assigned"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Core models
# ---------------------------------------------------------------------------


class GoalInput(BaseModel):
    """Minimal input model for creating a goal.

    This is ALL the human needs to provide. Everything else (IDs, timestamps,
    status) is auto-generated by the system.
    """

    title: str
    description: str
    constraints: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    priority: GoalPriority = GoalPriority.MEDIUM
    target_services: list[str] = Field(default_factory=list)


class Goal(BaseModel):
    """What the human wants done — the PRIMARY human input.

    A Goal captures intent at the highest level: natural-language description,
    constraints the agent must respect, and acceptance criteria for completion.
    """

    goal_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    title: str
    description: str
    constraints: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    priority: GoalPriority = GoalPriority.MEDIUM
    target_services: list[str] = Field(default_factory=list)
    target_paths: list[str] = Field(default_factory=list)
    created_by: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    status: GoalStatus = GoalStatus.DRAFT
    metadata: Optional[dict[str, Any]] = None


class AgentTask(BaseModel):
    """A single unit of work for an agent, derived from a Goal.

    Tasks are the atomic work items that agents execute. Each task inherits
    constraints from the parent goal and may have task-specific constraints
    added during decomposition.
    """

    task_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    goal_id: uuid.UUID
    title: str
    description: str
    target_files: list[str] = Field(default_factory=list)
    target_services: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    depends_on: list[uuid.UUID] = Field(default_factory=list)
    estimated_risk: RiskLevel = RiskLevel.LOW
    status: TaskStatus = TaskStatus.PENDING

    # Lease fields (set when claimed via LeaseManager)
    claimed_by: Optional[str] = None
    claimed_at: Optional[datetime] = None
    lease_expires_at: Optional[datetime] = None

    # Worktree fields (set when project has a repo_url)
    worktree_path: Optional[str] = None
    branch_name: Optional[str] = None


class TaskBreakdown(BaseModel):
    """How a goal gets decomposed into agent-sized work."""

    goal_id: uuid.UUID
    tasks: list[AgentTask] = Field(default_factory=list)
