"""Pydantic v2 models for the Projects Layer.

Projects sit above Goals and represent a scoped body of work that decomposes
into milestones, each containing one or more goals.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field

from src.goals.models import GoalPriority

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class ProjectStatus(str, enum.Enum):
    """Lifecycle status of a project."""

    DRAFT = "draft"
    PLANNING = "planning"
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class MilestoneStatus(str, enum.Enum):
    """Lifecycle status of a milestone within a project."""

    PENDING = "pending"
    ACTIVE = "active"
    COMPLETED = "completed"
    BLOCKED = "blocked"


# ---------------------------------------------------------------------------
# Core models
# ---------------------------------------------------------------------------


class Milestone(BaseModel):
    """A phase or checkpoint within a project, containing one or more goals."""

    milestone_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    title: str
    description: str = ""
    order: int  # sequence within project
    status: MilestoneStatus = MilestoneStatus.PENDING
    goal_ids: list[uuid.UUID] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)


class ProjectInput(BaseModel):
    """Minimal input model for creating a project.

    This is what the human provides. Everything else (IDs, timestamps,
    status, milestones) is auto-generated by the system.
    """

    title: str
    description: str
    constraints: list[str] = Field(default_factory=list)
    priority: GoalPriority = GoalPriority.MEDIUM
    target_services: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)


class Project(BaseModel):
    """A scoped body of work containing milestones and goals.

    Projects are the highest-level planning construct. They decompose into
    milestones (phases), each of which contains goals that further decompose
    into agent tasks.
    """

    project_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    title: str
    description: str
    status: ProjectStatus = ProjectStatus.DRAFT
    priority: GoalPriority = GoalPriority.MEDIUM
    constraints: list[str] = Field(default_factory=list)
    target_services: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    milestones: list[Milestone] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)

    # Git repo fields (Phase 3: worktree code workflow)
    repo_url: Optional[str] = None
    repo_local_path: Optional[str] = None
    default_branch: str = "main"
